### ISSUE TITLE
Global Follow

### ISSUE THREAD

**Issue by patschi** [FriendsOfFlarum/follow-tags#10]
It would be quite handy to be able to follow all discussions across all tags, so speaking to have a global "Follow" button on the main site.

**Comment by datitisev** [comment]
Hm, not sure if this falls in the scope of this ext. I guess it could, and then you can ignore specific tags instead of manually following the rest? 🤔 *Shouldn't* be hard to implement, not sure if we want that in this ext though.

**Comment by patschi** [comment]
It's  great for admins or mods to keep track about new discussions across the whole forum - even when new gets added. Therefore I thought it might be worth filing a feature request here :)

**Comment by luceos** [comment]
I agree with @datitisev ; I see no reason why this should be part of the follow-tags extension because this has no relation with tags; it's a global event subscription.

Have you checked this? https://extiverse.com/extension/fof/subscribed
