### ISSUE TITLE
Enabling the extension breaks the full version of the website

### ISSUE THREAD

**Issue by sakibarifin** [FriendsOfFlarum/follow-tags#14]
After enabling it, I get,
> "Something went wrong while trying to load the full version of this site. Try hard-refreshing this page to fix the error." 

error message.

**Comment by datitisev** [comment]
Can you provide us with an error from the flarum log located at storage/logs/flarum-<date>.log

**Comment by sakibarifin** [comment]
> Can you provide us with an error from the flarum log located at storage/logs/flarum-.log

The last modified file in that folder is two days old.

**Comment by datitisev** [comment]
The date of whenever you tried enabling the extension.

**Comment by sakibarifin** [comment]
> The date of whenever you tried enabling the extension.

I tried that today. But there is no log dated today.

**Comment by datitisev** [comment]
Can you check the response of the request using the developer tools? The Network tab should have a list of the requests made, and I think /api/extensions is the one when enabling an ext.

**Comment by datitisev** [comment]
Closing due to not enough info. I'
