### ISSUE TITLE
Performance issue with tag subscription state

### ISSUE THREAD

**Issue by luceos** [FriendsOfFlarum/follow-tags#17]
```php
        if ($event->isSerializer(TagSerializer::class)
            && ($state = $event->model->stateFor($event->actor))) {
            $event->attributes['subscription'] = $state->subscription;
        }
```

This causes over 300 queries to run on larger forums.

**Comment by askvortsov1** [comment]
What if we added a tag state serializer, and attached the tag state as an include? That should allow us to use one big query via a join instead of this

**Comment by luceos** [comment]
I can give that a shot, or if you are up to it.. feel free.

**Comment by askvortsov1** [comment]
Go for it!

**Comment by luceos** [comment]
Solving this issue depends on https://github.com/flarum/core/issues/2177, which has to be tackled first.

**Comment by datitisev** [comment]
Hopefully version `0.4.0` improves the performance.
