### ISSUE TITLE
Hidden tag filter not working

### ISSUE THREAD

**Issue by tariqwalji** [FriendsOfFlarum/follow-tags#23]
When looking at tags or /all, discussions from hidden tags were still showing up.

There was a small typo which incorrectly selected discussions belonging to hidden tags.

**Comment by tariqwalji** [comment]
Fix applied to #22

**Comment by datitisev** [comment]
I can't reproduce this.

**Comment by Marty** [comment]
I have the same issue. But I'm still running beta.13 as some extensions are not compatible yet.

Tags I marked with "Hiding" are still showing up on "All Discussions" page.

**Comment by imorland** [comment]
Included in release `0.6.1`

**Comment by clarkwinkelmann** [comment]
For some reason I did not notice this issue and just spend some time investigating it on a client forum.

There's one thing to look for to reproduce, it's the tag ID.

The bug actually means that if you mark any tag as hidden, tag ID 1 will be hidden from the homepage, and only that tag.

So when testing by hiding tag ID 1, you won't actually notice the issue.
