### ISSUE TITLE
Additional languages

### ISSUE THREAD

**Issue by Wulfheart** [FriendsOfFlarum/follow-tags#59]
I need some translations in German. Would you be willing to merge a PR with German translations?

**Comment by dsevillamartin** [comment]
Thanks for the PR. Sadly, we won't be merging it as we've decided to only maintain English locale and leave other languages to language packs (you can read more about why [here](https://discuss.flarum.org/d/19971-extensions-translation-in-their-own-repository-or-in-language-pack)).
 
Feel free to PR to a language pack with these translations, but I'll be closing the PR.
 
Thank you!
