### ISSUE TITLE
Body css error on web browser max-width: 768px

### ISSUE THREAD

**Issue by Litalino** [FriendsOfFlarum/follow-tags#65]
Current behavior

As shown in the attached screenshot, there is space in body. This affects the user experience of the interface.

Body css error on web browser max-width: 768px (@media @phone {})

Before
![B1](https://github.com/FriendsOfFlarum/follow-tags/assets/99712477/9d8b0a6a-6086-42cb-8448-d78ebe0093cd)

After 
```
@media @phone {
    body {overflow-y: auto;}
}
```
![B2](https://github.com/FriendsOfFlarum/follow-tags/assets/99712477/36d17a33-ae1b-4a71-9c19-adba776bb23a)

Environment

Flarum version: 1.8.2

**Comment by imorland** [comment]
Fixed in #66
