### ISSUE TITLE
N+1 Queries

### ISSUE THREAD

**Issue by rafaucau** [FriendsOfFlarum/follow-tags#72]
## Bug Report

**Current Behavior**
When the extension is enabled, there are a lot of queries to the database when loading the discussion list.
This line is responsible for this:
https://github.com/FriendsOfFlarum/follow-tags/blob/b76d70b1b58f8e7e9d1470232106340ab19c6752/src/AddTagSubscriptionAttribute.php#L23

**Steps to Reproduce**
1. Enable Clockwork
2. Load the Discussion list, e.g., Homepage
3. Observe the number of database queries executed

**Expected Behavior**
The subscription state should be eagerly loaded to minimize the number of database queries.

**Screenshots**

![image](https://github.com/FriendsOfFlarum/follow-tags/assets/25438601/89af636c-a677-4831-8854-0f7adde20c63)

**Environment**
- Flarum version: 1.8.5
- Extension version: 1.2.2

**Additional Context**
This issue was addressed in #45 but reverted in #46.

**Comment by dsevillamartin** [comment]
That reversion seems simply due to the state for a tag not existing... which is a valid scenario if the user hasn't configured anything about the tags that use the user state. So not 100% sure why it was just reverted instead of adding a null check.

Change goes from
![image](https://github.com/FriendsOfFlarum/follow-tags/assets/6401250/c72a9454-d040-4a3c-a5be-0c9cfc8fc1f3)
to
![image](https://github.com/FriendsOfFlarum/follow-tags/assets/6401250/3a837e45-5a66-4454-a15a-23720c4fcbac)

**Comment by rafaucau** [comment]
@DavideIadeluca I am experiencing an issue with the subscription state on my forum. On some tag pages, the subscription state is missing, but only on certain tags. Additionally, changing the follow status for these tags has no effect; the API returns null regardless of my selection:

![image](https://github.com/FriendsOfFlarum/follow-tags/assets/25438601/6e3163e6-dff3-4712-a7af-923677c13614)
![image](https://github.com/FriendsOfFlarum/follow-tags/assets/25438601/120d1097-16ca-482a-84ce-a7dcc25f87cb)

However, the `tag_user` table reflects the changes, while the tag page always shows the status as not followed (null/default).

I cannot reproduce this issue on a clean installation of Flarum. I checked on my forum with all extensions disabled except for Tags and Follow Tags, and the problem still persists. It might be related to the number of tags, above which the status does not load. I have 2544 tags in my database.

I have tested everything and noticed that the API query params includes `state`. This seems like a random issue. Additionally, when I use the [My Tags extension](https://github.com/android-com-pl/my-tags), I can see the list of followed tags changing as I navigate between tag pages, as if the relationships in the discussion list sometimes returns the followed state for certain tags and sometimes do not.

Do you have any suggestions on what could be causing this issue or what else I could try?

**Comment by rafaucau** [comment]
This resolves issue my:
```js
extend(DiscussionListState.prototype, 'requestParams', function(this: DiscussionListState, params) {
  if (typeof params.include === 'string') {
    params.include = [params.include];
  } else {
    params.include?.push('tags.state');
  }
});

```

**Comment by rafaucau** [comment]
I have found the cause: https://github.com/flarum/framework/issues/4007

**Comment by dsevillamartin** [comment]
This is interesting. I attempted a fix - can you see if #73 fixes all those instances for you? It should still improve performance over v1.2.3 (though not as much)

**Comment by rafaucau** [comment]
This solves the problem, but for the best performance it would be worth fixing this issue in Flarum
| Before | After |
|--------|-------|
|   ![image](https://github.com/user-attachments/assets/375acea6-edbe-4e7f-bee9-b2e02eb55c57)     |  ![image](https://github.com/user-attachments/assets/c44f2c34-4226-4641-a77c-6f7e67eed06b)   |

**Comment by dsevillamartin** [comment]
I agree, but once it's fixed in Flarum it should be fine in follow tags. The queries made in that PR are less if the actor was the first to have a tag state created, I believe - or if they visit a tag directly I think. I'm not 100% sure of when the state passed is for the correct user, but I do believe at least it makes a few less queries sometimes.

**Comment by dsevillamartin** [comment]
I pushed `v1.2.4` with that
