### ISSUE TITLE
Mail Message ID Domain is incorrect

### ISSUE THREAD

**Issue by tankerkiller125** [FriendsOfFlarum/follow-tags#9]
When most messages get sent via Flarum the message ID looks something like: `08572391c6de314c9e488a6763c7d3c2@flarum.domain.tld` however when emails are sent for this extension they are sent using a message ID like: `08572391c6de314c9e488a6763c7d3c2@swift.generated` although this is generally speaking fine and emails will still get delivered it can cause some spam filters to flag the messages as more suspicious or in some cases send messages straight to spam.

**Comment by datitisev** [comment]
Hm not sure why this would be, the ext uses the flarum mailing system...

**Comment by tankerkiller125** [comment]
I'm not sure why this is either, I only noticed it because I was doing some general checks on some emails and I just so happened to notice the discrepancy. Maybe theirs something weird with the Flarum core mailer itself and the way it handles extension emails?

**Comment by datitisev** [comment]
I'm to close this unless we get more info at some point.
